// src/modules/profile-setup/ui/vue/components/DniHelpModal.vue
<script setup lang="ts">
import styles from '../../shared/styles/DniHelpModal.module.css';
import Icon from './Icon.vue';

const props = defineProps<{
  isOpen: boolean;
}>();

const emit = defineEmits<{
  close: [];
}>();
</script>

<template>
  <div v-if="props.isOpen" :class="styles.backdrop">
    <section aria-label="Ayuda sobre el DNI" aria-modal="true" :class="styles.modal" role="dialog">
      <span :class="styles.iconBadge">
        <Icon name="id-card" />
      </span>
      <h2>Ayuda sobre el DNI</h2>
      <p>Introduce 8 números seguidos de la letra de control, por ejemplo 12345678Z.</p>
      <p>La letra no es decorativa: se calcula a partir del número. ESO es una regla de dominio.</p>
      <button :class="styles.closeButton" type="button" @click="emit('close')">
        Cerrar
        <Icon name="x" />
      </button>
    </section>
  </div>
</template>

// src/modules/profile-setup/ui/components/DniHelpModal.tsx
import { Icon } from './Icon';
import styles from './DniHelpModal.module.css';

type DniHelpModalProps = {
  isOpen: boolean;
  onClose: () => void;
};

export function DniHelpModal({ isOpen, onClose }: DniHelpModalProps) {
  if (!isOpen) return null;

  return (
    <div className={styles.backdrop}>
      <section aria-modal="true" aria-label="Ayuda sobre el DNI" className={styles.modal} role="dialog">
        <span className={styles.iconBadge}>
          <Icon name="id-card" />
        </span>
        <h2>Ayuda sobre el DNI</h2>
        <p>Introduce 8 números seguidos de la letra de control, por ejemplo 12345678Z.</p>
        <p>La letra no es decorativa: se calcula a partir del número. ESO es una regla de dominio.</p>
        <button className={styles.closeButton} type="button" onClick={onClose}>
          Cerrar
          <Icon name="x" />
        </button>
      </section>
    </div>
  );
}
