// src/modules/profile-setup/ui/vue/components/InterestsStep.vue
<script setup lang="ts">
import { reactive, toRaw, watch } from 'vue';
import type { FieldErrors, Interests } from '../../../domain/models/profile-setup';
import styles from '../../shared/styles/StepForm.module.css';
import FormField from './FormField.vue';
import Icon from './Icon.vue';
import SelectField from './SelectField.vue';

const props = defineProps<{
  value: Interests;
  errors: FieldErrors;
}>();

const emit = defineEmits<{
  back: [];
  next: [value: Interests];
}>();

const form = reactive(structuredClone(props.value));

watch(
  () => props.value,
  (value) => {
    Object.assign(form, structuredClone(value));
  },
  { deep: true },
);

function submit() {
  emit('next', structuredClone(toRaw(form)));
}
</script>

<template>
  <form :class="styles.form" @submit.prevent="submit">
    <header :class="styles.heading">
      <h2>Gustos e intereses</h2>
      <p>Estos datos ayudan a explicar el flujo de validación sin meter reglas en los componentes.</p>
    </header>

    <div :class="styles.grid">
      <FormField id="music" v-model="form.music" icon="music" label="Música" placeholder="Jazz, indie, clásica..." :error="props.errors.music" />
      <FormField id="sports" v-model="form.sports" icon="activity" label="Deportes" placeholder="Natación, running..." :error="props.errors.sports" />
      <FormField id="hobbies" v-model="form.hobbies" icon="sparkles" label="Hobbies" placeholder="Lectura, cocina..." :error="props.errors.hobbies" />
      <FormField id="culturalInterests" v-model="form.culturalInterests" icon="message" label="Intereses culturales" placeholder="Teatro, museos..." :error="props.errors.culturalInterests" />
      <SelectField
        id="socialActivityLevel"
        v-model="form.socialActivityLevel"
        full-width
        icon="users"
        label="Nivel de actividad social"
        :error="props.errors.socialActivityLevel"
        :options="[
          { label: 'Selecciona una opción', value: '' },
          { label: 'Bajo', value: 'low' },
          { label: 'Medio', value: 'medium' },
          { label: 'Alto', value: 'high' },
        ]"
      />
    </div>

    <div :class="styles.actions">
      <button :class="styles.secondaryButton" type="button" @click="emit('back')">
        <Icon :class-name="styles.buttonIcon" name="arrow-left" />
        Anterior
      </button>
      <button :class="styles.primaryButton" type="submit">
        Siguiente
        <Icon :class-name="styles.buttonIcon" name="arrow-right" />
      </button>
    </div>
  </form>
</template>

// src/modules/profile-setup/ui/components/interests-step.tsx
import { useState } from 'react';
import type { FieldErrors, Interests } from '../../domain/models/profile-setup';
import { FieldError } from './field-error';

type InterestsStepProps = {
  value: Interests;
  errors: FieldErrors;
  onBack: () => void;
  onNext: (value: Interests) => void;
};

export function InterestsStep({ value, errors, onBack, onNext }: InterestsStepProps) {
  const [form, setForm] = useState(value);

  return (
    <form
      className="step-card"
      onSubmit={(event) => {
        event.preventDefault();
        onNext(form);
      }}
    >
      <h2>2. Gustos, hobbies e intereses</h2>
      <label>
        Música
        <input value={form.music} onChange={(event) => setForm({ ...form, music: event.target.value })} />
      </label>
      <FieldError id="music-error" message={errors.music} />

      <label>
        Deportes
        <input value={form.sports} onChange={(event) => setForm({ ...form, sports: event.target.value })} />
      </label>
      <FieldError id="sports-error" message={errors.sports} />

      <label>
        Hobbies
        <input value={form.hobbies} onChange={(event) => setForm({ ...form, hobbies: event.target.value })} />
      </label>
      <FieldError id="hobbies-error" message={errors.hobbies} />

      <label>
        Intereses culturales
        <input value={form.culturalInterests} onChange={(event) => setForm({ ...form, culturalInterests: event.target.value })} />
      </label>
      <FieldError id="culturalInterests-error" message={errors.culturalInterests} />

      <label>
        Nivel de actividad social
        <select
          value={form.socialActivityLevel}
          onChange={(event) => setForm({ ...form, socialActivityLevel: event.target.value as Interests['socialActivityLevel'] })}
        >
          <option value="">Selecciona una opción</option>
          <option value="low">Bajo</option>
          <option value="medium">Medio</option>
          <option value="high">Alto</option>
        </select>
      </label>
      <FieldError id="socialActivityLevel-error" message={errors.socialActivityLevel} />

      <div className="actions between">
        <button type="button" onClick={onBack}>Anterior</button>
        <button type="submit">Siguiente</button>
      </div>
    </form>
  );
}
