// src/modules/profile-setup/ui/vue/components/PreferencesStep.vue
<script setup lang="ts">
import { reactive, toRaw, watch } from 'vue';
import type { FieldErrors, Preferences } from '../../../domain/models/profile-setup';
import styles from '../../shared/styles/StepForm.module.css';
import CheckboxField from './CheckboxField.vue';
import FormField from './FormField.vue';
import Icon from './Icon.vue';
import SelectField from './SelectField.vue';
import TextAreaField from './TextAreaField.vue';

const props = defineProps<{
  value: Preferences;
  errors: FieldErrors;
  isSaving: boolean;
}>();

const emit = defineEmits<{
  back: [];
  submit: [value: Preferences];
}>();

const form = reactive(structuredClone(props.value));

watch(
  () => props.value,
  (value) => {
    Object.assign(form, structuredClone(value));
  },
  { deep: true },
);

function submitForm() {
  emit('submit', structuredClone(toRaw(form)));
}
</script>

<template>
  <form :class="styles.form" @submit.prevent="submitForm">
    <header :class="styles.heading">
      <h2>Preferencias y objetivos</h2>
      <p>Último paso: definimos expectativas y consentimientos antes de guardar el perfil.</p>
    </header>

    <div :class="styles.grid">
      <TextAreaField id="appGoal" v-model="form.appGoal" icon="target" label="Qué buscas en la app" placeholder="Cuéntanos brevemente tu objetivo..." :error="props.errors.appGoal" />
      <SelectField
        id="communicationPreference"
        v-model="form.communicationPreference"
        icon="send"
        label="Preferencia de comunicación"
        :error="props.errors.communicationPreference"
        :options="[
          { label: 'Selecciona una opción', value: '' },
          { label: 'Email', value: 'email' },
          { label: 'Teléfono', value: 'phone' },
          { label: 'Sin comunicaciones', value: 'none' },
        ]"
      />
      <FormField id="cityOrArea" v-model="form.cityOrArea" icon="map-pin" label="Ciudad o zona" placeholder="Madrid centro" :error="props.errors.cityOrArea" />
      <SelectField
        id="expectedUsageFrequency"
        v-model="form.expectedUsageFrequency"
        icon="repeat"
        label="Frecuencia esperada de uso"
        :error="props.errors.expectedUsageFrequency"
        :options="[
          { label: 'Selecciona una opción', value: '' },
          { label: 'Diaria', value: 'daily' },
          { label: 'Semanal', value: 'weekly' },
          { label: 'Mensual', value: 'monthly' },
        ]"
      />
      <CheckboxField id="acceptsTerms" v-model="form.acceptsTerms" label="Acepto los términos del servicio" :error="props.errors.acceptsTerms" />
      <CheckboxField id="acceptsPrivacy" v-model="form.acceptsPrivacy" label="Acepto la política de privacidad" :error="props.errors.acceptsPrivacy" />
    </div>

    <div :class="styles.actions">
      <button :class="styles.secondaryButton" :disabled="props.isSaving" type="button" @click="emit('back')">
        <Icon :class-name="styles.buttonIcon" name="arrow-left" />
        Anterior
      </button>
      <button :class="styles.primaryButton" :disabled="props.isSaving" type="submit">
        {{ props.isSaving ? 'Guardando...' : 'Guardar perfil' }}
        <Icon :class-name="styles.buttonIcon" name="arrow-right" />
      </button>
    </div>
  </form>
</template>

// src/modules/profile-setup/ui/components/preferences-step.tsx
import { useState } from 'react';
import type { FieldErrors, Preferences } from '../../domain/models/profile-setup';
import { FieldError } from './field-error';

type PreferencesStepProps = {
  value: Preferences;
  errors: FieldErrors;
  isSaving: boolean;
  onBack: () => void;
  onSubmit: (value: Preferences) => void;
};

export function PreferencesStep({ value, errors, isSaving, onBack, onSubmit }: PreferencesStepProps) {
  const [form, setForm] = useState(value);

  return (
    <form
      className="step-card"
      onSubmit={(event) => {
        event.preventDefault();
        onSubmit(form);
      }}
    >
      <h2>3. Preferencias y objetivos</h2>
      <label>
        Qué buscas en la app
        <textarea value={form.appGoal} onChange={(event) => setForm({ ...form, appGoal: event.target.value })} />
      </label>
      <FieldError id="appGoal-error" message={errors.appGoal} />

      <label>
        Preferencia de comunicación
        <select
          value={form.communicationPreference}
          onChange={(event) => setForm({ ...form, communicationPreference: event.target.value as Preferences['communicationPreference'] })}
        >
          <option value="">Selecciona una opción</option>
          <option value="email">Email</option>
          <option value="phone">Teléfono</option>
          <option value="none">Sin comunicaciones</option>
        </select>
      </label>
      <FieldError id="communicationPreference-error" message={errors.communicationPreference} />

      <label>
        Ciudad o zona
        <input value={form.cityOrArea} onChange={(event) => setForm({ ...form, cityOrArea: event.target.value })} />
      </label>
      <FieldError id="cityOrArea-error" message={errors.cityOrArea} />

      <label>
        Frecuencia esperada de uso
        <select
          value={form.expectedUsageFrequency}
          onChange={(event) => setForm({ ...form, expectedUsageFrequency: event.target.value as Preferences['expectedUsageFrequency'] })}
        >
          <option value="">Selecciona una opción</option>
          <option value="daily">Diaria</option>
          <option value="weekly">Semanal</option>
          <option value="monthly">Mensual</option>
        </select>
      </label>
      <FieldError id="expectedUsageFrequency-error" message={errors.expectedUsageFrequency} />

      <label className="checkbox-row">
        <input
          checked={form.acceptsTerms}
          type="checkbox"
          onChange={(event) => setForm({ ...form, acceptsTerms: event.target.checked })}
        />
        Acepto los términos del servicio
      </label>
      <FieldError id="acceptsTerms-error" message={errors.acceptsTerms} />

      <label className="checkbox-row">
        <input
          checked={form.acceptsPrivacy}
          type="checkbox"
          onChange={(event) => setForm({ ...form, acceptsPrivacy: event.target.checked })}
        />
        Acepto la política de privacidad
      </label>
      <FieldError id="acceptsPrivacy-error" message={errors.acceptsPrivacy} />

      <div className="actions between">
        <button disabled={isSaving} type="button" onClick={onBack}>Anterior</button>
        <button disabled={isSaving} type="submit">{isSaving ? 'Guardando...' : 'Guardar perfil'}</button>
      </div>
    </form>
  );
}
